import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal.family = "GoMono Nerd Font"

size = 18

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Left", mods = "Control", action = "Copy" },
]
