"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Josh Burgess"
email = "josh@joshb.io"

# override user.email if the repository is located under ~/oss
[[--scope]]
--when.repositories = ["~/work"]
[--scope.user]
email = "josh.burgess@bigideaslearning.com"

[ui]
editor = "nvim"
bookmark-list-sort-keys = ["name"]
default-command = ["log", "--reversed"]

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
